#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 
# Starts a Hadoop MapReduce History Server
# 
# chkconfig: 2345 85 10
# description: Hadoop MapReduce History Server

source /etc/profile.d/hadoop.sh
source /etc/profile.d/java.sh
source /etc/rc.d/init.d/functions
source ${HADOOP_HOME}/etc/hadoop/hadoop-env.sh

RETVAL=0
PIDFILE="${HADOOP_MAPRED_PID_DIR}/mapred-mapred-historyserver.pid"
desc="Hadoop MapReduce History Server daemon"

start() {
  echo -n $"Starting $desc (hadoop-historyserver): "
  daemon --user mapred ${HADOOP_HOME}/sbin/mr-jobhistory-daemon.sh --config "${HADOOP_CONF_DIR}" start historyserver
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch /var/lock/subsys/hadoop-historyserver
  return $RETVAL
}

stop() {
  echo -n $"Stopping $desc (hadoop-historyserver): "
  daemon --user mapred ${HADOOP_HOME}/sbin/mr-jobhistory-daemon.sh --config "${HADOOP_CONF_DIR}" stop historyserver
  RETVAL=$?
  sleep 5
  echo
  [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/hadoop-historyserver $PIDFILE
}

restart() {
  stop
  start
}

checkstatus(){
  echo $"$desc $(status -p $PIDFILE)"
  RETVAL=$?
}

condrestart(){
  [ -e /var/lock/subsys/hadoop-historyserver ] && restart || :
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    checkstatus
    ;;
  restart)
    restart
    ;;
  condrestart)
    condrestart
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|condrestart}"
    exit 1
esac

exit $RETVAL